export enum TopologyMappingCode {
    unspecified = "unspecified",
    namespaceDelegation = "namespaceDelegation",
    decentralizedNamespaceDefinition = "decentralizedNamespaceDefinition",
    ownerToKeyMapping = "ownerToKeyMapping",
    synchronizerTrustCertificate = "synchronizerTrustCertificate",
    participantPermission = "participantPermission",
    partyHostingLimits = "partyHostingLimits",
    vettedPackages = "vettedPackages",
    partyToParticipant = "partyToParticipant",
    synchronizerParametersState = "synchronizerParametersState",
    mediatorSynchronizerState = "mediatorSynchronizerState",
    sequencerSynchronizerState = "sequencerSynchronizerState",
    sequencingDynamicParametersState = "sequencingDynamicParametersState",
    partyToKeyMapping = "partyToKeyMapping",
    lsuAnnouncement = "lsuAnnouncement",
    sequencerConnectionSuccessor = "sequencerConnectionSuccessor",
}
